config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'projects', to: 'pages#projects'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alex Bottenberg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="index-background">
  <div class="container-index d-flex justify-content-around">
    <div class="button">
      <%= link_to '<<', root_path, class: "btn-back"%>
    </div>

    <div class="content">
      <p>Having completed a web development bootcamp with Le Wagon, I am skilled in HTML, CSS, Bootstrap, JavaScript, SQL, Ruby, and Rails.
      <br>
      I am a creative and driven individual with a BA Fashion Design degree from the University of Westminster. With 6 years previous experience in the fashion industry as a menswear designer, I pride myself on my eye for detail and design. I am skilled in Adobe Photoshop, Illustrator and InDesign, research, illustration, and multi product fashion design.
      <br>
      I am excited to combine my new skills with my previous experience and begin a new career in tech.
      </p>
      <%= link_to 'Github', 'https://github.com/abottenberg/', target: 'blank', class: 'link-social'  %>
      <br>
      <%= link_to 'LinkedIn', 'https://www.linkedin.com/in/alex-bottenberg/', target: 'blank', class: 'link-social' %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="d-flex">
    <%= link_to '<<', root_path, class: "btn-back-contact"%>
    <p class="email">adbotte</p>
  </div>
  <p class="email">nberg@gma</p>
  <p class="email">il.com</p>
</div>

app/views/pages/home.html.erb
<div class="home-background">
  <div class="menu d-flex justify-content-end align-items-end">

    <div class="dropdown">
      <a class="btn-menu" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Menu
      </a>

      <div class="dropdown-menu dropright" aria-labelledby="dropdownMenuLink">
        <%= link_to 'Projects', projects_path, class: "dropdown-item"%>
        <%= link_to 'About', about_path, class: "dropdown-item"%>
        <%= link_to 'Contact', contact_path, class: "dropdown-item"%>
      </div>
    </div>
  </div>
</div>

app/views/pages/projects.html.erb
<div class="container">
  <%= link_to '<<', root_path, class: "btn-back"%>
  <h1 class="heading-center">Projects</h1>
  <div class="d-flex justify-content-around">
    <div class="ts">
      <p class="number">1</p>
      <%= link_to 'http://www.turningseasons.co.uk/', target: 'blank' do %>
        <%= image_tag "lettuce.png", alt: "turnip", width: 360, class: 'card' %>
        <p class="title">Turning Seasons</p>
        <p class="hidden-text">A group project.<br>Turning Seasons aims to promote an understanding of food seasons and make it easy for you to cook locally sourced, seasonal produce. Unlike other recipe apps and websites, we only show recipes who's main ingredients are currently in season.</p>
      <% end %>
    </div>

    <div class="cocktail">
      <p class="number">2</p>
      <%= link_to 'https://bottenberg-cocktails.herokuapp.com/', target: 'blank' do %>
        <%= image_tag "martini.png", alt: "cocktail", width: 280, class: 'card' %>
        <p class="title">Mr Cocktail</p>
        <p class="hidden-text">An individual project.<br>A cocktail recipe app.</p>
      <% end %>
    </div>

    <div class="superhero">
      <p class="number">3</p>
      <%= link_to 'https://superhero-bnb.herokuapp.com/', target: 'blank' do %>
        <%= image_tag "superman.png", alt: "superman", width: 360, class: 'card' %>
        <p class="title">Superhero BnB</p>
        <p class="hidden-text">A group project.<br>Build your superhero and super villain teams.<br>Add your own supers.</p>
      <% end %>
    </div>


  </div>
</div>